"""
NotionService — thin async wrapper around Notion REST API v1.

Scope for R11: create a page under an existing parent (page or database)
with a title and free-form text content. Used by MARK (doc publish),
CATCH (meeting notes), PULSE (briefing archive), RAW (research log).

Env vars:
    NOTION_API_KEY — required. Internal integration token.

Notion caveats:
    - rich_text blocks are capped at 2000 characters each → long content
      is chunked into multiple paragraph blocks.
    - parent_id accepted as either a page ID (default) or database ID —
      we default to page_id for simplicity; callers using a database
      should pass `parent_type="database"`.

Usage:
    from services.notion import NotionService
    svc = NotionService()
    result = await svc.create_page(
        parent_id="abc-def-123",
        title="API Documentation",
        content="# API\\n\\nGenerated by MARK.",
    )
    # result = {"created": True, "page_id": "...", "url": "https://notion.so/..."}
"""

from __future__ import annotations

import logging
import os
from typing import Any, Dict, List

import httpx

logger = logging.getLogger("cruz.services.notion")

_NOTION_API = "https://api.notion.com/v1"
_NOTION_VERSION = "2022-06-28"
_NOTION_TEXT_LIMIT = 2000  # Notion's per-block rich_text character cap


class NotionService:
    """Async wrapper around a minimal slice of the Notion REST API."""

    def __init__(self) -> None:
        pass

    async def create_page(
        self,
        parent_id: str,
        title: str,
        content: str,
        parent_type: str = "page",
    ) -> Dict[str, Any]:
        """
        Create a new Notion page under an existing parent.

        Args:
            parent_id:   parent page ID (or database ID if parent_type="database")
            title:       page title (appears in sidebar)
            content:     body text; chunked into blocks if >2000 chars
            parent_type: "page" (default) or "database"

        Returns {"created": True, "page_id": str, "url": str}.
        Raises RuntimeError on missing token or non-2xx response.
        """
        token = os.environ.get("NOTION_API_KEY", "").strip()
        if not token:
            raise RuntimeError(
                "NOTION_API_KEY is not set — cannot create Notion page. "
                "Set it in .env (internal integration token from notion.so/my-integrations)."
            )

        parent = (
            {"database_id": parent_id}
            if parent_type == "database"
            else {"page_id": parent_id}
        )

        payload = {
            "parent": parent,
            "properties": {
                "title": {
                    "title": [
                        {"text": {"content": title}}
                    ]
                }
            },
            "children": _build_paragraph_blocks(content),
        }

        async with httpx.AsyncClient(
            headers={
                "Authorization": f"Bearer {token}",
                "Content-Type": "application/json",
                "Notion-Version": _NOTION_VERSION,
            },
            timeout=20.0,
        ) as client:
            resp = await client.post(f"{_NOTION_API}/pages", json=payload)

        if resp.status_code >= 300:
            raise RuntimeError(
                f"Notion create_page failed: HTTP {resp.status_code} — {resp.text}"
            )

        data = resp.json()
        page_id = data.get("id", "")
        url = data.get("url", "")
        logger.info(
            "Notion page created: id=%s url=%s title=%s",
            page_id, url, title,
        )
        return {"created": True, "page_id": page_id, "url": url}


# ── Helpers ───────────────────────────────────────────────────────────────

def _build_paragraph_blocks(content: str) -> List[Dict[str, Any]]:
    """
    Split content into paragraph blocks, each under Notion's 2000-char cap.

    Notion truncates rich_text silently past the cap, so chunking is
    required for any generated documentation of non-trivial length.
    """
    blocks: List[Dict[str, Any]] = []
    if not content:
        return blocks
    for i in range(0, len(content), _NOTION_TEXT_LIMIT):
        chunk = content[i : i + _NOTION_TEXT_LIMIT]
        blocks.append(
            {
                "object": "block",
                "type": "paragraph",
                "paragraph": {
                    "rich_text": [
                        {"type": "text", "text": {"content": chunk}}
                    ]
                },
            }
        )
    return blocks
