"""uuid_conversations_and_user_preferences

Migrate conversations.id and messages.conversation_id from SERIAL/INTEGER
to UUID so they match the UUIDs generated by the API layer.
Also adds users.preferences JSONB for procedural memory (Phase 4+).

Revision ID: 0002
Revises: 0001
Create Date: 2026-04-13
"""

from typing import Sequence, Union

import sqlalchemy as sa
from alembic import op

revision: str = "0002"
down_revision: Union[str, Sequence[str], None] = "0001"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ── users: add preferences JSONB ─────────────────────────────────────
    op.add_column("users", sa.Column("preferences", sa.JSON, nullable=True))

    # ── Recreate conversations with UUID primary key ───────────────────────
    # Drop dependent tables first (FK order)
    op.drop_index("idx_messages_conversation", table_name="messages")
    op.drop_table("messages")
    op.drop_index("idx_conversations_trace_id", table_name="conversations")
    op.drop_table("conversations")

    op.create_table(
        "conversations",
        sa.Column(
            "id",
            sa.String(36),
            primary_key=True,
            comment="UUID generated by API layer",
        ),
        sa.Column("user_id", sa.Integer, sa.ForeignKey("users.id"), nullable=True),
        sa.Column("device", sa.String(50), nullable=True),
        sa.Column("title", sa.Text, nullable=True),
        sa.Column("context", sa.JSON, nullable=True),
        sa.Column(
            "created_at", sa.TIMESTAMP, server_default=sa.text("NOW()"), nullable=False
        ),
        sa.Column(
            "updated_at", sa.TIMESTAMP, server_default=sa.text("NOW()"), nullable=False
        ),
    )

    op.create_table(
        "messages",
        sa.Column("id", sa.Integer, primary_key=True),
        sa.Column(
            "conversation_id",
            sa.String(36),
            sa.ForeignKey("conversations.id"),
            nullable=False,
        ),
        sa.Column("role", sa.String(20), nullable=False),
        sa.Column("content", sa.Text, nullable=False),
        sa.Column("metadata", sa.JSON, nullable=True),
        sa.Column(
            "created_at", sa.TIMESTAMP, server_default=sa.text("NOW()"), nullable=False
        ),
    )

    op.create_index("idx_conversations_id", "conversations", ["id"])
    op.create_index("idx_messages_conversation", "messages", ["conversation_id"])


def downgrade() -> None:
    op.drop_index("idx_messages_conversation", table_name="messages")
    op.drop_table("messages")
    op.drop_index("idx_conversations_id", table_name="conversations")
    op.drop_table("conversations")

    op.create_table(
        "conversations",
        sa.Column("id", sa.Integer, primary_key=True),
        sa.Column("user_id", sa.Integer, sa.ForeignKey("users.id"), nullable=True),
        sa.Column("trace_id", sa.String(64), nullable=True),
        sa.Column("device", sa.String(50), nullable=True),
        sa.Column("context", sa.JSON, nullable=True),
        sa.Column(
            "created_at", sa.TIMESTAMP, server_default=sa.text("NOW()"), nullable=False
        ),
    )

    op.create_table(
        "messages",
        sa.Column("id", sa.Integer, primary_key=True),
        sa.Column(
            "conversation_id",
            sa.Integer,
            sa.ForeignKey("conversations.id"),
            nullable=False,
        ),
        sa.Column("role", sa.String(20), nullable=False),
        sa.Column("content", sa.Text, nullable=False),
        sa.Column("metadata", sa.JSON, nullable=True),
        sa.Column(
            "created_at", sa.TIMESTAMP, server_default=sa.text("NOW()"), nullable=False
        ),
    )

    op.create_index("idx_conversations_trace_id", "conversations", ["trace_id"])
    op.create_index("idx_messages_conversation", "messages", ["conversation_id"])

    op.drop_column("users", "preferences")
